from app.services.embedding import local_embed

# Expected (index, value) pairs generated by running the ORIGINAL Node localEmbed
# (git show HEAD:backend/agent/extract/src/services/embedding.service.js) via
# `node -e` for the same two texts, before this module was ported to Python.
# The Python port must be bit-identical so new vectors mix consistently with
# any pre-existing rows written by the Node service.
NODE_REFERENCE = {
    "fintech startup at seed stage": [
        (196, -0.4472135954999579),
        (278, 0.4472135954999579),
        (598, -0.4472135954999579),
        (1019, -0.4472135954999579),
        (1493, -0.4472135954999579),
    ],
    "Golden Gate Ventures VC firm investing in fintech": [
        (536, -0.35355339059327373),
        (847, -0.35355339059327373),
        (975, -0.35355339059327373),
        (1019, -0.35355339059327373),
        (1106, 0.35355339059327373),
        (1186, -0.35355339059327373),
        (1417, -0.35355339059327373),
        (1464, 0.35355339059327373),
    ],
}


def _nonzero(vec):
    return [(i, x) for i, x in enumerate(vec) if x != 0]


def test_matches_node_localembed_reference():
    for text, expected in NODE_REFERENCE.items():
        assert _nonzero(local_embed(text)) == expected


def test_deterministic_for_same_input():
    text = "fintech startup at seed stage"
    assert local_embed(text) == local_embed(text)


def test_is_l2_normalized():
    vec = local_embed("a b c d e fintech health-tech e-commerce")
    norm = sum(x * x for x in vec) ** 0.5
    assert abs(norm - 1.0) < 1e-9


def test_empty_text_is_zero_vector():
    assert local_embed("") == [0.0] * 1536
